SEC_PER_FRAME = 0.3 # seconds
IMAGE_WIDTH = 256
IMAGE_HEIGHT = 256

THRESHOLD_SSIM_AUDIO = 0.4
THRESHOLD_SSIM = 0.6
THRESHOLD_ORB = 0.90
THRESHOLD_ORB_MATCH = 0.95
HASH_CUTOFF = 5

SEQUENCE_THRESHOLD = 4 # seconds
MIN_LENGTH_SEQUENCE = 5 # seconds
FRACTION_SIZE_PREINTRO = 0.35 #35 percentage
PREINTRO_START = 30 # limit for a preintro to start in seconds
DOWNSCALE_FACTOR = 10

MARGIN_BETWEEN_PITCH = 1
MIN_SEQ_LENGTH = 10 #seconds

SEGMENT_LENGTH = 0.1 #seconds
HASH_NAME = "hashes"
PITCH_NAME = "pitches"


DESCRIPTION_MATCHES_INTRO = "matches_intro"
DESCRIPTION_MATCHES = "matches"
DESCRIPTION_PITCHES = "pitches"
