SEC_PER_FRAME = 0.4 # seconds
IMAGE_WIDTH = 256
IMAGE_HEIGHT = 256

THRESHOLD_SSIM_AUDIO = 0.4
THRESHOLD_SSIM = 0.6
THRESHOLD_ORB = 0.90
THRESHOLD_ORB_MATCH = 0.95
HASH_CUTOFF = 5

SEQUENCE_THRESHOLD = 3 # seconds
MIN_LENGTH_SEQUENCE = 5 # seconds
DOWNSCALE_FACTOR = 10

AUDIO_SIZE_SPLITS = 1 #seconds
